#!/usr/bin/env bash
# setup/lib/90-video.sh — phase-2 video. Dispatches to a pluggable source
# module (setup/config/video-sources/${VIDEO_SOURCE}.sh) on the air role, and
# turns on wfb-ng's own rtsp@<codec>.service on the gs role. No-op entirely
# when VIDEO_ENABLE=0 -- nothing installed, no units touched, so a plain
# SSH+MAVLink install stays as small as it was before this stage existed.
#
# See setup/config/video-sources/rtsp.sh for the module contract (three
# functions: video_src_packages/video_src_validate/video_src_pipeline).
# Adding uvc/csi support later is a new file in that directory; nothing in
# this stage needs to change.

VIDEO_SOURCES_DIR="$HERE/config/video-sources"
VIDEO_SCRIPT_OUT=/usr/local/bin/wfb-video-air
VIDEO_UNIT_SRC="$HERE/config/systemd/wfb-video-air.service"
VIDEO_UNIT_OUT=/etc/systemd/system/wfb-video-air.service

stage_video() {
    if [ "$VIDEO_ENABLE" != "1" ]; then
        log "VIDEO_ENABLE=0 -- skipping the video stage entirely (no packages installed, no units touched)."
        return 0
    fi

    if [ "$ROLE" = "air" ]; then
        _video_air
    else
        _video_gs
    fi
}

# _video_load_module -- source config/video-sources/${VIDEO_SOURCE}.sh, or
# die with the list of what's actually available. 50-config.sh already
# checked this file exists before generating /etc/wifibroadcast.cfg, but
# --only lets stages run independently and out of order, so this stage
# re-checks rather than assuming an earlier one already did.
_video_load_module() {
    local mod="$VIDEO_SOURCES_DIR/${VIDEO_SOURCE}.sh"
    if [ ! -f "$mod" ]; then
        # `|| true` matters: under `set -e -o pipefail`, a failing `ls` (e.g.
        # the directory is somehow missing) would abort the script on this
        # assignment BEFORE the die() below ever runs -- the same class of
        # bug fixed in lib/30-driver.sh's _driver_dkms_field. This is only
        # building a helpful error message; it must never itself crash.
        local available
        available="$(ls "$VIDEO_SOURCES_DIR" 2>/dev/null | sed 's/\.sh$//' | tr '\n' ' ')" || true
        die "VIDEO_SOURCE='$VIDEO_SOURCE' has no matching module ($mod not found). Available: ${available:-none}."
    fi
    # shellcheck source=/dev/null
    source "$mod"
}

_video_air() {
    _video_load_module
    video_src_validate

    log "Installing video packages for source '$VIDEO_SOURCE'"
    local pkgs
    read -ra pkgs <<< "$(video_src_packages)"
    run apt-get install -y "${pkgs[@]}"

    log "Generating $VIDEO_SCRIPT_OUT"
    if [ "${DRY_RUN:-0}" = "1" ]; then
        log "[dry-run] would write $VIDEO_SCRIPT_OUT with the $VIDEO_SOURCE pipeline"
    else
        {
            echo "#!/usr/bin/env bash"
            echo "# GENERATED by setup/lib/90-video.sh from setup/link.conf (VIDEO_SOURCE=$VIDEO_SOURCE)."
            echo "# DO NOT EDIT HERE -- edit link.conf, then:"
            echo "#   sudo ./install.sh --role air --only 90-video"
            echo "set -e"
            video_src_pipeline
        } > "$VIDEO_SCRIPT_OUT"
        chmod 0755 "$VIDEO_SCRIPT_OUT"
        log "Wrote $VIDEO_SCRIPT_OUT"
    fi

    install_file "$VIDEO_UNIT_SRC" "$VIDEO_UNIT_OUT"
    run systemctl daemon-reload
    # `|| true` for the same reason as wifibroadcast@ in 70-services.sh: with
    # no camera plugged in yet, GStreamer fails fast and `enable --now`
    # surfaces that as its own exit code. Diagnose below instead of aborting.
    run systemctl enable --now wfb-video-air.service || true

    if [ "${DRY_RUN:-0}" = "1" ]; then
        return 0
    fi
    sleep 1
    if systemctl is-active --quiet wfb-video-air.service; then
        log "wfb-video-air.service is active."
    else
        warn "wfb-video-air.service did not stay up. Check:"
        warn "    journalctl -u wfb-video-air -e --no-pager"
        warn "For a clearer GStreamer error, run the generated script directly:"
        warn "    sudo $VIDEO_SCRIPT_OUT"
        warn "Common cause with no camera connected yet: 'Could not open resource"
        warn "for reading' / unreachable host -- expected until VIDEO_CAM_URL points"
        warn "at a real, reachable camera."
    fi
}

_video_gs() {
    if [ "$VIDEO_RTSP_SERVER" != "1" ]; then
        log "VIDEO_RTSP_SERVER=0 -- skipping rtsp@$VIDEO_CODEC. Video is still readable directly on udp://127.0.0.1:5600."
        return 0
    fi

    log "Enabling rtsp@$VIDEO_CODEC (ships in the wfb-ng package -- not reimplemented here)"
    run systemctl enable --now "rtsp@${VIDEO_CODEC}.service" || true

    if [ "${DRY_RUN:-0}" = "1" ]; then
        return 0
    fi
    sleep 1
    if systemctl is-active --quiet "rtsp@${VIDEO_CODEC}.service"; then
        log "rtsp@${VIDEO_CODEC} is active -- rtsp://<this-host>:8554/wfb"
    else
        warn "rtsp@${VIDEO_CODEC} did not come up. Check:"
        warn "    journalctl -u rtsp@${VIDEO_CODEC} -e --no-pager"
    fi
}
